services:
  catalogue-service:
    build:
      context: ./catalogue-service
      dockerfile: Dockerfile
    container_name: catalogue-service
    ports:
      - "5000:5000"
    volumes:
      - ./catalogue-service/instance:/app/instance
    networks:
      - purchase-system
    restart: unless-stopped

  cart_db:
      image: mongo:7.0
      container_name: cart_db
      ports:
        - "27017:27017"
      networks:
        - purchase-system

networks:
  purchase-system:
    driver: bridge