server:
  port: 8080

spring:
  output:
    ansi:
      enabled: ALWAYS
  main:
    banner-mode: off
  application:
    name: store-service

  # R2DBC config
  r2dbc:
    url: r2dbc:h2:mem:///library?options=DB_CLOSE_DELAY=-1;
    username: sa
    password: ""

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/cart_db}

# External Legacy Service
services:
  catalogue:
    base-url: ${CATALOGUE_SERVICE_URL:http://localhost:5000}
    timeout:
      response-ms: 2500
      sla-ms: 5000
    retry:
      max-attempts: 3
      initial-backoff-ms: 100


# Logging
logging:
  level:
    com:
      melodev: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} %clr(%-5level) [%10.10t] %30.30logger{2} : %msg %n"
